
CREATE TABLE IF NOT EXISTS couleur (
    idCouleur BIGINT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(255) UNIQUE NOT NULL,
    INTERVALLE1 DOUBLE NOT NULL,
    INTERVALLE2 DOUBLE NOT NULL
);

ALTER TABLE Status_Demande ADD COLUMN nbJours DOUBLE DEFAULT 0;
ALTER TABLE Status_Demande ADD COLUMN idCouleur BIGINT;
ALTER TABLE Status_Demande ADD FOREIGN KEY (idCouleur) REFERENCES couleur(idCouleur) ON DELETE SET NULL;

